/**
 * In this fiel all the error messages
 * or the success messages are stored
 * and shown when sankbar is called by API or method
 */

import { Error } from "../model/error/error.module";
export const ErrorMessgae: Error[] = [
  {
    1: "Query Failed",
    2: "Please enter a Mobile Number",
    3: "User Already Registered, Please login",
    4: "Please contact to the Company",
    5: "User Details",
    6: "User is not registered",
    7: "Please enter a Mobile Number or Otp",
    8: "Get OTP API error",
    9: "Verify OTP API error",
    10: "Resend OTP API error",
    11: "User Register Successfully",
    12: "Auth code error or not generated",
    13: "Image Not Uploaded",
    14: "Image Uploaded Successfully",
    15: "Image Is not Valid",
    16: "Image Not Updated",
    17: "Please enter workshop id",
    18: "No Jobcard with this workshop id",
    19: "Jobcards Details",
    20: "Please enter the Auth code",
    21: "You are not authorized to access this resource.",
    22: "Signature expired. Please log in again.",
    23: "Invalid token. Please log in again.",
    24: "NO jobcard Settings",
    25: "Please enter a Vehicle Number",
    26: "Please enter mode",
    27: "Customer Updated Successfully",
    28: "Customer Created Successfully",
    29: "Customer Allready created with this vechile number",
    30: "NO Data Found",
    31: "Lube Allready Exist",
    32: "New Lube Added Successfully",
    33: "New Spare Added Successfully",
    34: "New Job Added Successfully",
    35: "Spare Allready Exist",
    36: "Job Allready Exist",
    37: "Jobcard Allready Exist with this Jobcard Number",
    38: "Jobcard Created Successfully",
    39: "Voice name allready exist",
    40: "Customer Voice Added Successfully",
    41: "No Staff for this Workshop",
    42: "Settings Saved Successfully",
    43: "No Jobcard Found",
    44: "Image Deleted Successfully",
    45: "No Reminder For this Jobcard",
    46: "Reminder For this Jobcard",
    47: "Error in updateing Reminders",
    48: "Reminders allready set",
    49: "Message Send Successfully",
    50: "Message Not Send Successfully",
    51: "No Jobcard",
    52: "Please enter Search Keyword or Vehicle Number",
    53: "No Vehicle found",
    54: "No Inventory Found with this Part Number",
    55: "Inventory Deleted Successfully",
    56: "Please Enter Workshop Id",
    57: "Workshop May be Deleted or not registered",
    58: "Updated Successfully",
    59: "Settings Updated Successfully",
    60: "Settings Updated Successfully",
    61: "Settings Updated Successfully",
    62: "Settings Updated Successfully",
    63: "Mobile Number Updated Successfully",
    64: "No Data",
    65: "Mail Send",
    66: "Invalid Email ID",
    67: "Jobcard Not Created",
    68: "Cutsomer Id Updated",
    69: "Jobcard Deleted Successfully",
    70: "Updated Lube Successfully",
    71: "Updated Spare Successfully",
    72: "Updated Job  Successfully",
    73: "Lsat History Dates",
    74: "No History for this Vehicle",
    75: "No History data",
    76: "History data",
    77: "Staff Created Successfully",
    78: "Query Failed while creating Staff",
    79: "Staff with same Mobile Number already exists",
    80: "Staff Member Deleted Successfully",
    104: "Vehicle Not present",
    105: "supplier already added",
    106: "User Updated Successfully",
    107: "User Created Successfully",
    108: "User Allready created with this Mobile number",
    109: "Group Created Successfully",
  },
];
